apiVersion: v1
kind: Secret
metadata:
  name: order-secrets
  namespace: payment-service
type: Opaque
data:
  DATABASE_USER: b3JkZXJ1c2Vy            # orderuser
  DATABASE_PASSWORD: b3JkZXJwYXNzd29yZA==  # orderpassword
  JWT_SECRET: b3JkZXJzZXJ2aWNlLWp3dC1zZWNyZXQta2V5LTEyMzQ1Ng==  # orderservice-jwt-secret-key-123456